LA:
Added operators (axpy(), mult()) to uBlasVector.

PyDOLFIN:

Rewrote dolfin-swig in Python. Minor fixes to elasticity demo, works
with uBlas now.

diff --git a/src/config/dolfin-swig.template b/src/config/dolfin-swig.template
--- a/src/config/dolfin-swig.template
+++ b/src/config/dolfin-swig.template
@@ -1,126 +1,144 @@
-#/bin/bash
+#!/usr/bin/env python
+
+import os, sys
+from commands import getoutput
 
 # Simple tool to automatically convert a compiled FFC form (in DOLFIN-SWIG
 # format) into a Python module.
 
-name=${1%.h}
-lowername=`echo $name | tr 'A-Z' 'a-z'`
-modulename=$lowername"form"
-
-
-swigfile=$modulename.i
-
-#echo $name
-#echo $lowername
-#echo $modulename
-#echo $swigfile
-
-usage()
-{
-   cat << EOF
-Usage: dolfin-swig [form source file]
+usage = """
+Usage: %s [form source file]
 
 Example: dolfin-swig Poisson3D.h
+""" % os.path.basename(sys.argv[0])
 
-EOF
-   exit $1
-}
+if len(sys.argv) < 2:
+    print usage
 
-if test $# -eq 0; then
-    usage 1 1>&2
-fi
+name = sys.argv[1]
+name = name.rstrip(".h")
+lowername = name.lower()
+modulename = lowername + "form"
 
-if ! test -e $1; then
-    echo "Cannot find $1."
-    exit 1
-fi
+swigfile = modulename + ".i"
 
+#if ! test -e $1; then
+#    echo "Cannot find $1."
+#    exit 1
+#fi
 
-echo Generating the SWIG interface file for the $name form
+print "Generating the SWIG interface file for the %s form" % name
 
-cat > $swigfile <<EOF
-%module $modulename
+swigsource = """%%module %s
 
-%{
+%%{
 #include <dolfin.h>
 #include <string>
 
-#include "$name.h"
+#include \"%s.h\"
 
 using namespace dolfin;
-%}
+%%}
 
-%typemap(python,in) real = double; 
-%typemap(python,out) real = double; 
-%typemap(python,in) uint = int; 
-%typemap(python,out) uint = int; 
+%%typemap(python,in) real = double; 
+%%typemap(python,out) real = double; 
+%%typemap(python,in) uint = int; 
+%%typemap(python,out) uint = int; 
 
 // Typemaps for dolfin::real array arguments in virtual methods
 // probably not very safe
-%typemap(directorin) dolfin::real [] {
+%%typemap(directorin) dolfin::real [] {
   {
     // Custom typemap
-    \$input = SWIG_NewPointerObj((void *) \$1_name, \$1_descriptor, \$owner);
+    $input = SWIG_NewPointerObj((void *) $1_name, $1_descriptor, $owner);
   }
 }
 
-%typemap(directorin) dolfin::real const [] {
+%%typemap(directorin) dolfin::real const [] {
   {
     // Custom typemap
-    \$input = SWIG_NewPointerObj((void *) \$1_name, \$1_descriptor, \$owner);
+    $input = SWIG_NewPointerObj((void *) $1_name, $1_descriptor, $owner);
   }
 }
 
+%%include \"typemaps.i\"
+%%include \"std_string.i\"
 
+%%include \"carrays.i\"
 
+//%%include \"%s.i\"
 
-%include "typemaps.i"
-%include "std_string.i"
+%%array_functions(dolfin::real, realArray);
 
-%include "carrays.i"
+%%feature(\"director\") Function;
+%%feature(\"director\") BoundaryCondition;
+%%feature(\"director\") ODE;
 
-%array_functions(dolfin::real, realArray);
+%%ignore dolfin::dolfin_set;
+%%ignore dolfin::dolfin_set_aptr;
 
-%feature("director") Function;
-%feature("director") BoundaryCondition;
-%feature("director") ODE;
-
-%ignore dolfin::dolfin_set;
-%ignore dolfin::dolfin_set_aptr;
-
-%import "dolfin.h"
-%import "dolfin/constants.h"
+%%import \"dolfin.h\"
+%%import \"dolfin/constants.h\"
 
 /* function imports */
 
-%import "dolfin/Function.h"
+%%import \"dolfin/Function.h\"
 
 /* fem imports */
 
-%include "dolfin/FiniteElement.h"
+%%include \"dolfin/FiniteElement.h\"
 
 /* form imports */
 
-%include "dolfin/Form.h"
-%include "dolfin/BilinearForm.h"
-%include "dolfin/LinearForm.h"
+%%include \"dolfin/Form.h\"
+%%include \"dolfin/BilinearForm.h\"
+%%include \"dolfin/LinearForm.h\"
 
 /* form include */
 
-%include "$name.h"
-EOF
+%%include \"%s.h\"
+""" % (modulename, name, name, name)
 
-echo Building the Python module
+swigoutput = open(swigfile, 'w')
+swigoutput.write(swigsource)
+swigoutput.close()
 
-swig -python -c++ -nodefault -dirprot `dolfin-config --includes` -o ${modulename}_wrap.cpp $swigfile
+print "Building the Python module"
+
+debugout = getoutput("swig -python -c++ -nodefault -dirprot `dolfin-config --includes` -o %s_wrap.cpp %s" % (modulename, swigfile))
+
+print debugout
+
+# FIXME: Workaround for apparent bug in SWIG, try to fix the bug.
+
+interfacefile = open("%s_wrap.cpp" % modulename)
+
+tmpfile = open("tmp.cpp", 'w')
+
+stext = "dolfin::%s::dolfin::" % name
+rtext = "dolfin::"
+
+for s in interfacefile.xreadlines():
+    tmpfile.write(s.replace(stext, rtext))
+
+interfacefile.close()
+tmpfile.close()
+
+debugout = getoutput("mv tmp.cpp %s_wrap.cpp" % modulename)
+
+
 
 # FIXME:
 # Compilation still not compiler-independent
 
-`dolfin-config --compiler` `dolfin-config --swigcflags` `dolfin-config --cflags` -I. -g -fPIC  -c -o ${modulename}_wrap.o ${modulename}_wrap.cpp
+debugout = getoutput("`dolfin-config --compiler` `dolfin-config --swigcflags` `dolfin-config --cflags` -I. -g -fPIC  -c -o %s_wrap.o %s_wrap.cpp" % (modulename, modulename))
+
+print debugout
 
 # FIXME:
 # Generating shared library still not compiler-independent (syntax likely
 # only works for GCC)
 
-`dolfin-config --linker` -g -shared ${modulename}_wrap.o -o _${modulename}.so `dolfin-config --libs`
+debugout = getoutput("`dolfin-config --linker` -g -shared %s_wrap.o -o _%s.so `dolfin-config --libs`" % (modulename, modulename))
+
+print debugout
